### ISSUE TITLE
support for newer protobuff or update requirements.txt

### ISSUE THREAD

**Issue by psifertex** [PistonMiner/binaryninja-bindiff-viewer#3]
The latest protobuf isn't compatible with the BD viewer.

Recommend either updating https://github.com/PistonMiner/binaryninja-bindiff-viewer/blob/master/requirements.txt to pin on the latest version compatible (looks like 3.20.1 at a glance?) or else updating the plugin with a newer protobuf (or both which sounds like the plan 😉 )

**Comment by PistonMiner** [comment]
Resolved in b57d0ae4d42ed8654cb87e11c765f8339eb4aa67
